# To run from IntelliJ, enable Advanced/Allow the default Docker socket to be used in Docker Desktop settings.
services:

  db:
    image: postgres
    restart: always
    environment:
      # Defaults, this database should already exist in Postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    # Expose ports so that we can create the database with gradle
    ports:
      - 5432:5432

  # Tracing
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 16686:16686
      - 14268:14268
    hostname: jaeger

  # From https://www.split.io/blog/containerization-spring-boot-docker/
  # Should be replaced(?) by com.palantir.docker/docker-compose
  # For now build with `./gradlew build` then `docker compose up` from the project root directory
  # See also hello-spring-boot.Dockerfile
  # The service should wait(?) for its dependencies, this is done with something like wait-for-it.sh
  # or with [testcontainers](https://java.testcontainers.org/)
  hello-spring-boot:
    build:
      context: ./docker
      dockerfile: hello-spring-boot.Dockerfile
    restart: on-failure
    depends_on:
      - jaeger
      - db
    ports:
      - 8080:8080
