# To run from IntelliJ, enable Advanced/Allow the default Docker socket to be used in Docker Desktop settings.
services:
  # Tracing
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 16686:16686
      - 14268:14268
    hostname: jaeger

  # From https://www.split.io/blog/containerization-spring-boot-docker/
  # Should be replaced(?) by com.palantir.docker/docker-compose
  # For now build with `./gradlew build` then `docker compose up` from the project root directory
  # See also Dockerfile
  # The service should wait(?) for its dependencies, this is done with something like wait-for-it.sh
  # or with [testcontainers](https://java.testcontainers.org/)
  hello-spring-boot:
    build: ./
    restart: on-failure
    depends_on:
      - jaeger
    ports:
      - 8080:8080
