# To run from IntelliJ, enable Advanced/Allow the default Docker socket to be used in Docker Desktop settings.
services:
  # Tracing
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4318:4318"
    # Optional: create a "docker_hello-spring-boot" network so that all services can talk to each other
    # Default: docker_default
    networks:
      - hello-spring-boot
networks:
  hello-spring-boot:
